site_name: PhysiLab
site_description: Cuaderno de laboratorio digital para ensayos de cinematica con CLI en Python.
site_url: https://samsof28.github.io/physilab-project/
repo_url: https://github.com/SamSof28/physilab-project
repo_name: SamSof28/physilab-project

theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo  
      accent: cyan     
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs 
    - navigation.sections
    - toc.integrate 
    - content.code.copy 

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]

nav:
  - Inicio: index.md
  - Primeros pasos: getting-started.md
  - Guía de usuario:
    - Comandos CLI: user-guide/commands.md
    - Persistencia: user-guide/persistence.md
  - Arquitectura: architecture.md
  - Referencia: reference.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite